server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
  # 配置了这个之后，kill 会打印：
  # 2025-06-25 16:30:50.116  INFO 10032 --- [extShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
  # 2025-06-25 16:30:50.227  INFO 10032 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
  shutdown: graceful

mycar:
  brand: lambojini
  price: 8000000

spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root!
    driver-class-name: com.mysql.cj.jdbc.Driver
    # initialization-mode: always 表示每次应用启动时都执行数据源的初始化（包括 schema.sql 和 data.sql），可选值有 always、embedded、never
    initialization-mode: always
    # schema: 指定初始化数据库结构的 SQL 脚本路径，通常用于建表
    schema: classpath:transactional_listener_demo/schema.sql
    # data: 指定初始化数据库数据的 SQL 脚本路径，通常用于插入初始数据
    data: classpath:transactional_listener_demo/data.sql
    # platform: 指定数据库平台类型（如 mysql、h2 等），可用于选择不同的脚本
    platform: mysql
  jpa:
    hibernate:
      # ddl-auto: none 表示 JPA 不会自动创建、更新或校验数据库表结构，常用于生产环境
      ddl-auto: none
  # 配置自定义的 banner
  banner:
    location: classpath:banner.txt
  # 自定义的启动器配置
  xxl:
    job:
      enabled: true


#debug: true